### ISSUE TITLE
Support for the "style" attribute

### ISSUE THREAD

**Issue by fuggla** [globalcitizen/svglover#8]
I tried to draw a svg created in Inkscape, but the shapes are always black. I think it's because Inkscape stores the fill color in the `style` attribute:

```svg
style="fill:#ff0000"
```
rather than:

```svg
fill="#ff0000"
```

Is it possible to add support for `style` in svglover? I had a look at the code but couldn't really figure out where to start.

**Comment by globalcitizen** [comment]
Yes, that seems to be the case.

Unfortunately I have not touched lua in a good while (since 2016) so do not have a current environment configured. I could look in to this.

However, I also believe there is a new SVG library available, [tove2d](https://love2d.org/wiki/T%C3%96VE) which also apparently supports animation. 

Please take a look at that and let me know your thoughts. If you prefer this one, I will look to add the feature. If you prefer that one, let me know and I won't bother.

**Comment by fuggla** [comment]
For convenience sake I usually go for pure lua implementations, so I do prefer svglover over tove2d. But I tested with the `style` attr, and it works, so I'll close this issue. Thanks for offering to add this feature though!
